config/routes.rb
Rails.application.routes.draw do

  resource :calendar, only: [:show], controller: :calendar

  get 'static_pages/home' 
  get 'static_pages/account' => 'static_pages#account', as: :account
  get 'articles#article_calendar' => 'articles#article_calendar', as: :article_calendar
  
  devise_for :users
  resources :articles do 
    resources :comments
  end 

  root 'static_pages#home'

end

app/models/article.rb
class Article < ActiveRecord::Base

	has_many :comments, dependent: :destroy
	belongs_to :user
	default_scope -> { order(created_at: :desc) }

	validates :name, :content, presence: true
	validates :user_id, presence: true

	def useremail
		article.user.email
	end


	def self.search(query)  
	    if query  
	      where('name LIKE ? OR content LIKE ?', "%#{query}%", "%#{query}%")  
	    else  
	      where(nil) 
	    end  
  	end
	

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :article
    belongs_to :user
  	default_scope -> { order(created_at: :desc) }
  	validates :article_id, presence: true
  	validates :user_id, presence: true
  	validates :name, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles, dependent: :destroy
  has_many :comments

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/default_image.png"
        validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


  protected
  def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password) }
        devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :password, :remember_me) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :full_name, :description, :password, :current_password, :password_confirmation, :avatar) }
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :set_comment
  respond_to :html
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.search(params[:search])
    if params[:search].present?
      if @articles.empty?
        @search = "No records found for  '#{params[:search]}'"
      else 
        @search = "Your query- '#{params[:search]}' yielded #{@articles.count} results."
      end 
    end 
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    #@comment = Comment.new
    @comment = @article.user.comments.build
    if !user_signed_in?
    flash[:alert] = "Please sign in to post a comment"
    end 

  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.create(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.'} 
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    redirect_to article_calendar_url, notice: 'Article was successfully destroyed.'
    
  end

  def article_calendar
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @articles = Article.all
    @user = current_user
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :content)
    end

    def set_comment
      @art = Article.find_by(params[:article_id])
    end 

   
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def show
  	@date = params[:date] ? Date.parse(params[:date]) : Date.today
    @articles = Article.all
    @user = current_user
    #@users = User.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
 

  def new
    @artile = Article.find(params[:id])
    @comment = @article.user.comments.build
  end
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)
    @comment.user_id = current_user.id
    
    respond_to do |format|
      format.js {}
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @article = Article.find(params[:article_id])
    @comment.destroy
    redirect_to article_path(@article), notice: "Comment was successfully destroyed." 
      
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:name, :article_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @articles = Article.search(params[:search])
    if params[:search].present?
      if @articles.empty?
        @search = "No records found for  '#{params[:search]}'"
      else 
        @search = "Your query- '#{params[:search]}' yielded #{@articles.count} results."
      end 
    end   
  	if !user_signed_in?
    flash[:success] = "Please signup/signin in to post an article"
    end 
  end

  def account
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper

	 def calendar(date = Date.today, &block)
    	Calendar.new(self, date, block).table
  	 end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/_form.html.erb
<%= bootstrap_form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.text_area :content, :size => "60x6" %>
  </div>
    <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/articles/article_calendar.html.erb
<% provide(:title, 'by Date') %>

<h3><strong>My Articles:</strong></h3><hr>
<div class="row">
	<div class="col-md-12">
		<ol type="1">
		<% @user.articles.each do |article| %>
		            <li>
		            	<%= link_to (truncate strip_tags(simple_format(article.name)), :length => 30, :separator => ' '), article %>
		            </li><br />
		<% end %> 
		</ol>
	</div><br />
	<div>
	<%= link_to 'Articles by Date', calendar_path, class: 'btn btn-success' %>
	</div>
	
</div>

app/views/articles/edit.html.erb
<% provide(:title, 'Edit Article') %>
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% provide(:title, 'Home') %>

<h3><strong>Articles</strong></h3><hr>
<p style="color:red"> <strong><%= @search %> </strong></p>

<div class="article-index">
    <ol type="1">
	    <% @articles.each do |article| %>
		      <h5><li><%= link_to article.name.titleize, article %></li></h5> &nbsp &nbsp 
		      <i class="art-post"> posted on <%= article.created_at.strftime("%A, %d %b %Y") %>&nbsp  by <%= article.user.email %></i>&nbsp &nbsp 
		      <% if article.user.email == current_user.email %>
			      <%= link_to 'Edit', edit_article_path(article) %> &nbsp &nbsp
			      <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
		      <% end %><br /><br />

			  <%= truncate strip_tags(simple_format(article.content)), :length => 420, :separator => ' ' %> &nbsp
			  <%= link_to 'Click here for Full article', article %><br /><hr>
	    <% end %>
    </ol>
</div><br>

app/views/articles/new.html.erb
<% provide(:title, 'New Article') %>
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% provide(:title, @article.name.titleize) %>

<p>
  <strong><h3> <%= @article.name.titleize %></h3></strong> &nbsp
  <i class="art-post"> by <%= @article.user.email %> </i>
  <% if user_signed_in? %>
    <% if @article.user.email == current_user.email %>
      <i style="float:right"><%= link_to 'Edit Article', edit_article_path(@article) %></i>
    <% end %>
  <% end %>
</p>

<p style="color:green">
  <strong>Description:</strong>
  <%= simple_format(@article.content) %>
</p>
<h4 id="comment-invoke">Comments: </h4>
<div id="comment-holder">

<% if @article.comments.any? %><br /><hr> 
      <p id="comment_count"><%= @article.comments.count %> &nbsp comments:</p>

  <div class="comment-box"> 
    <ul id="nalla">
          <%= render @article.comments %>
    </ul><br />
  </div>
<% else %>
  <p>0 comments.</p>
<% end %>
  <p id="shiva"></p>

  <div id="com_form">
    <%= render 'comments/form'%><br><br>
  </div>
</div>

app/views/calendar/show.html.erb
<div class="row">
	<div class="col-md-3">
		<h3><strong>Articles by Date:</strong></h3><hr>
		<% @user.articles.each do |article| %>
		         <ul>
		            <li>
		            	<%= link_to (truncate strip_tags(simple_format(article.name)), :length => 30, :separator => ' '), article %>
		            </li>
		         </ul>
		<% end %> 
	</div>
	<div class="col-md-9">
		<div class="row">
			<div class="col-md-12">
				<div id="calendar">
					<h3 id="month">
				      <%= link_to calendar_path(date: @date - 1.month), class: "btn btn" do %>
				       <strong><</strong> 
				      <% end %>
				      <%= "#{@date.strftime("%B")} #{@date.year}" %>
				      <%= link_to calendar_path(date: @date + 1.month), class: "btn btn" do %>
				       <strong>></strong>
				      <% end %>
				    </h3>
				   

				    <%= calendar @date do |date| %>
				      <%= date.day %>
				      <% @user.articles.each do |article| %>
				         <ul>
				           <% if article.created_at.strftime("%D") == date.strftime("%D") %>
				            <li>
				            	<%= link_to (truncate strip_tags(simple_format(article.name)), :length => 30, :separator => ' '), article %>
				            </li>
				           <% end %>
				         </ul> 
				       <% end %>
				    <% end %>
				</div><br /> <br />
			</div>
		</div>	
	</div>
</div>

app/views/comments/_comment.html.erb
            <li> 
              <%= comment.name %> &nbsp &nbsp<br /> 
              <i class="com-post">posted <%= time_ago_in_words(comment.created_at) %> ago
                 &nbsp by <%= comment.user.email %> &nbsp &nbsp &nbsp 
                <% if user_signed_in? %>
                  <% if comment.user.email == current_user.email %> 
                        <p class="com-del"><%= link_to 'Delete', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-warning' %></p>
                  <% elsif @article.user.email == current_user.email %>
                        <p class="com-del"><%= link_to 'Delete', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-warning' %></p>
                  <% end %>
                <% end %>
              </i>
            </li>

app/views/comments/_form.html.erb
<%= bootstrap_form_for([@article, @comment],remote: true, html: {id: "com_art"}) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %><br />
  <ul class="errors"></ul>
  <div class="field">
    <%= f.text_area :name, :placeholder => 'your comment here..', :size => '60x6' %>
  </div>
    <%= f.hidden_field :article_id, value: @article.id %>

  
  <div class="actions" id="krishna">
    <%= f.submit :class => 'btn btn-primary'%>
  </div>
  
<% end %>

app/views/comments/create.js.erb
<% if @comment.save %>
	$("#nalla").html("<%= j render(@article.comments) %> ");
	$("#comment_name").val("");
	$("#shiva").html("");
	$("#shiva").css("background-color", "#fff");
	

<% else %>
	$("#shiva").html("Comment can't be blank!");
	$("#shiva").css("background-color", "#f2dede");
	$("#shiva").css("color", "#a94442")
	$("#shiva").css("padding", "15px")
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Article</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.article %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><h3> <%= @article.name.titleize %></h3></strong> &nbsp
  <i class="art-post"> by <%= @article.user.email %> </i>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.content %>
</p>
<% if @article.comments.any? %><br /><hr> 
<h4>Comments: </h4>
<div class="comment-box"> <h5><%= @article.comments.count %>&nbsp comments:</h5>
          
  <ul><% @article.comments.each do |comment| %>
           <li><%= comment.name %> &nbsp &nbsp<br /> <i class="com-post">posted  &nbsp by <%= comment.user.email %> &nbsp &nbsp &nbsp 
                  <% if comment.user.email == current_user.email %> 
                    <p class="com-del"><%= link_to 'Delete', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-warning' %></p>
                  <% elsif @article.user.email == current_user.email %>
                    <p class="com-del"><%= link_to 'Delete', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-warning' %></p>
                  <% end %></i></li>
               <% end  %></ul><br />
               </div>
          <%= render 'comments/form' %>
<% else %>
<br/><p>0 comments.</p>
          <%= render 'comments/form' %>
<% end %>

app/views/comments/new.js.erb
$("#shiva").html("<%= flash[:alert] %>")

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <li><%= link_to '', articles_path, :class => 'glyphicon glyphicon-home' %></li> 
      <% else %>
        <li><%= link_to '', root_path, :class => 'glyphicon glyphicon-home' %></li>
      <% end %>
      </ul>
    </div>
    <div>
      <ul class="nav navbar-nav">
              <% if user_signed_in? %>
              <li><%= link_to 'New Article', new_article_path %></li>
              <li><%= link_to 'My Articles', article_calendar_path %></li>
              <li><%= link_to 'My Account',  account_path %> </li>
              <% end %>
      </ul>
      <ul class="nav navbar-nav pull-right">  
      <% if user_signed_in? %>
        <li style="margin-top:8px"> 
            <%= form_tag articles_path, class: "form-inline", role: "form", :method => 'get' do %> 
              <div class="form-group has-success has-feedback"> 
                <%= text_field_tag :search, params[:search], :placeholder => "search articles", class: " search-query form-control" %> 
                <%= button_tag "", class: "glyphicon glyphicon-search", style: "padding:12px;" %>
              </div>  
            <% end %>
        </li>     
      

        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
      <% else %>
        <li style="margin-top:8px"> <%= form_tag articles_path, class: "form-inline", role: "form", :method => 'get' do %> 
              <div class="form-group has-success has-feedback"> 
                <%= text_field_tag :search, params[:search], :placeholder => "search articles", class: " search-query form-control" %>  
                <%= submit_tag "Search", :name => nil, class: "btn btn-default"%>
              </div>  
            <% end %>
        </li> 
        <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li> 
        <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Articles - <%= yield(:title) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="row">

	<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>

	<div class="col-md-2">
		<% if user_signed_in? %>
			<%= image_tag current_user.avatar.url(:thumb), class: "img-square", style: "padding:20px" %>
			<%= current_user.email%>
		<% end %>
	</div>

	<div class="col-md-8">
		<%= yield %>
	</div>

	<div class="col-md-2">
	</div>
	
</div>

    

</body>
</html>

app/views/static_pages/about_us.html.erb
<h1>Welcome to My Blog </h1>
This Blog contains articles posted by various authors. Anyone who is signed up can post articles and comments.

app/views/static_pages/account.html.erb
	<div class="panel panel-default">
		<div class="panel-heading">
			<h2>Profile settings:</h2>
		</div>
		<div class="panel-body">
		  <h4>Edit your Profile: <%= link_to 'Click here', edit_user_registration_path, :class => 'btn btn-primary' %></h4
		</div>
	</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Index') %>

<h3>Articles</h3><hr>
<p style="color:red"> <strong><%= @search %> </strong></p>	
	<div class="article-index">
    <ol type="1">
    <% @articles.each do |article| %>
	      <h4><li><%= link_to article.name.titleize, article %></li></h4> &nbsp &nbsp 
	       <i class="art-post"> posted on <%= article.created_at.strftime("%A, %d %b %Y") %>&nbsp  by <%= article.user.email %></i>&nbsp &nbsp 
	      <br /><br />

	      <%= truncate strip_tags(simple_format(article.content)), :length => 420, :separator => ' ' %> &nbsp
	      <%= link_to 'Click here for Full article', article %>

	      <br /><hr>
	      
    <% end %>
    </ol>
    </div>

     

<br>